CXX = cl
CC = cl

CXXFLAGS = -EHsc
#CXXFLAGS = -GX
CXXFLAGSWIN = -DVMCQ_NEEDMAX
#CXXFLAGSWIN = -DVMCQ_NEEDMAX /Zm500
CFLAGS = -EHsc
#CFLAGS = -GX
WLIBS = kernel32.lib user32.lib gdi32.lib
LIBS =

TYPE1 = AllFriends
TYPE2 = NotFriends_NoTemplates
TYPE3 = NotFriends_NotMembers
TYPE4 = NotFriends_MostlyMembers

all: $(TYPE1) $(TYPE2) $(TYPE4) $(TYPE3) Other
#all: $(TYPE1) $(TYPE2) $(TYPE4) # for Visual C/C++ 6

AllFriends:
	mkdir $(TYPE1)
	$(CXX) $(CXXFLAGS) /Fe$(TYPE1)\testc.exe /Fo$(TYPE1)\testc.obj -I ..\$(TYPE1) testc.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE1)\testq.exe /Fo$(TYPE1)\testq.obj -I ..\$(TYPE1) testq.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE1)\testeq.exe /Fo$(TYPE1)\testeq.obj -I ..\$(TYPE1) testeq.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE1)\testmf.exe /Fo$(TYPE1)\testmf.obj -I ..\$(TYPE1) testmf.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE1)\testall.exe /Fo$(TYPE1)\testall.obj -I ..\$(TYPE1) testall.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE1)\testall2.exe /Fo$(TYPE1)\testall2.obj -I ..\$(TYPE1) $(CXXFLAGSWIN) testall2.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE1)\vgraphw.exe /Fo$(TYPE1)\vgraphw.obj -I ..\$(TYPE1) vgraphw.cpp $(WLIBS)
	$(CXX) $(CXXFLAGS) /Fe$(TYPE1)\qgraphw.exe /Fo$(TYPE1)\qgraphw.obj -I ..\$(TYPE1) qgraphw.cpp $(WLIBS)

NotFriends_NoTemplates:
	mkdir $(TYPE2)
	$(CXX) $(CXXFLAGS) /Fe$(TYPE2)\testc.exe /Fo$(TYPE2)\testc.obj -I ..\$(TYPE2) testc.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE2)\testq.exe /Fo$(TYPE2)\testq.obj -I ..\$(TYPE2) testq.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE2)\testeq.exe /Fo$(TYPE2)\testeq.obj -I ..\$(TYPE2) testeq.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE2)\testmf.exe /Fo$(TYPE2)\testmf.obj -I ..\$(TYPE2) testmf.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE2)\testall.exe /Fo$(TYPE2)\testall.obj -I ..\$(TYPE2) testall.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE2)\testall2.exe /Fo$(TYPE2)\testall2.obj -I ..\$(TYPE2) $(CXXFLAGSWIN) testall2.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE2)\vgraphw.exe /Fo$(TYPE2)\vgraphw.obj -I ..\$(TYPE2) vgraphw.cpp $(WLIBS)
	$(CXX) $(CXXFLAGS) /Fe$(TYPE2)\qgraphw.exe /Fo$(TYPE2)\qgraphw.obj -I ..\$(TYPE2) qgraphw.cpp $(WLIBS)

NotFriends_NotMembers:
	mkdir $(TYPE3)
	$(CXX) $(CXXFLAGS) /Fe$(TYPE3)\testc.exe /Fo$(TYPE3)\testc.obj -I ..\$(TYPE3) testc.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE3)\testq.exe /Fo$(TYPE3)\testq.obj -I ..\$(TYPE3) testq.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE3)\testeq.exe /Fo$(TYPE3)\testeq.obj -I ..\$(TYPE3) testeq.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE3)\testmf.exe /Fo$(TYPE3)\testmf.obj -I ..\$(TYPE3) testmf.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE3)\testall.exe /Fo$(TYPE3)\testall.obj -I ..\$(TYPE3) testall.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE3)\testall2.exe /Fo$(TYPE3)\testall2.obj -I ..\$(TYPE3) $(CXXFLAGSWIN) testall2.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE3)\vgraphw.exe /Fo$(TYPE3)\vgraphw.obj -I ..\$(TYPE3) vgraphw.cpp $(WLIBS)
	$(CXX) $(CXXFLAGS) /Fe$(TYPE3)\qgraphw.exe /Fo$(TYPE3)\qgraphw.obj -I ..\$(TYPE3) qgraphw.cpp $(WLIBS)

NotFriends_MostlyMembers:
	mkdir $(TYPE4)
	$(CXX) $(CXXFLAGS) /Fe$(TYPE4)\testc.exe /Fo$(TYPE4)\testc.obj -I ..\$(TYPE4) testc.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE4)\testq.exe /Fo$(TYPE4)\testq.obj -I ..\$(TYPE4) testq.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE4)\testeq.exe /Fo$(TYPE4)\testeq.obj -I ..\$(TYPE4) testeq.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE4)\testmf.exe /Fo$(TYPE4)\testmf.obj -I ..\$(TYPE4) testmf.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE4)\testall.exe /Fo$(TYPE4)\testall.obj -I ..\$(TYPE4) testall.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE4)\testall2.exe /Fo$(TYPE4)\testall2.obj -I ..\$(TYPE4) $(CXXFLAGSWIN) testall2.cpp
	$(CXX) $(CXXFLAGS) /Fe$(TYPE4)\vgraphw.exe /Fo$(TYPE4)\vgraphw.obj -I ..\$(TYPE4) vgraphw.cpp $(WLIBS)
	$(CXX) $(CXXFLAGS) /Fe$(TYPE4)\qgraphw.exe /Fo$(TYPE4)\qgraphw.obj -I ..\$(TYPE4) qgraphw.cpp $(WLIBS)

Other:
	$(CXX) $(CXXFLAGS) testccc.cpp
	rem $(CC) $(CFLAGS) testcc.c $(LIBS)
	@echo --------------------------------------------------------------------------
	@echo Visual Studio C seems to implement complex.h differently, so don't compile
	@echo testcc.c  But, maybe your version will compile it - remove rem if you
	@echo want to try.
	@echo --------------------------------------------------------------------------

clean:
	del AllFriends NotFriends_NoTemplates NotFriends_NotMembers NotFriends_MostlyMembers testccc.exe testccc.obj testcc.exe testcc.obj
	rmdir AllFriends NotFriends_NoTemplates NotFriends_NotMembers NotFriends_MostlyMembers
